Fix wrong content of ec2ifscan - replacing with correct content

diff --git a/ec2ifscan b/ec2ifscan
--- a/ec2ifscan
+++ b/ec2ifscan
@@ -1,6 +1,29 @@
-# This task finds and configures elastic network interfaces
-# left in an unconfigured state.
+#!/bin/bash
 
-start on net-device-up IFACE=eth0
-task
-exec /sbin/ec2ifscan
+# Copyright (C) 2013 Amazon.com, Inc. or its affiliates.
+# All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License").
+# You may not use this file except in compliance with the License.
+# A copy of the License is located at
+#
+#    http://aws.amazon.com/apache2.0/
+#
+# or in the "license" file accompanying this file. This file is
+# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
+# OF ANY KIND, either express or implied. See the License for the
+# specific language governing permissions and limitations under the
+# License.
+
+if [ $UID -ne 0 ]; then
+  echo "error: ${0##*/} must be run as root"
+  exit 1
+fi
+
+for dev in $(find /sys/class/net/eth*) ; do
+  cfg="/etc/network/interfaces.d/${dev##*/}.cfg"
+  state=$(cat ${dev}/operstate)
+  if [ ! -e "${cfg}" ] && [ "${state}" == "down" ] ; then
+    echo 'add' > ${dev}/uevent
+  fi
+done
